// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        (unknown)
// source: kitchenpb/kitchen_messages.proto

package kitchenpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Events
type TicketAccepted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TicketID   string                 `protobuf:"bytes,1,opt,name=TicketID,proto3" json:"TicketID,omitempty"`
	OrderID    string                 `protobuf:"bytes,2,opt,name=OrderID,proto3" json:"OrderID,omitempty"`
	AcceptedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=AcceptedAt,proto3" json:"AcceptedAt,omitempty"`
	ReadyBy    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=ReadyBy,proto3" json:"ReadyBy,omitempty"`
}

func (x *TicketAccepted) Reset() {
	*x = TicketAccepted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kitchenpb_kitchen_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TicketAccepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketAccepted) ProtoMessage() {}

func (x *TicketAccepted) ProtoReflect() protoreflect.Message {
	mi := &file_kitchenpb_kitchen_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketAccepted.ProtoReflect.Descriptor instead.
func (*TicketAccepted) Descriptor() ([]byte, []int) {
	return file_kitchenpb_kitchen_messages_proto_rawDescGZIP(), []int{0}
}

func (x *TicketAccepted) GetTicketID() string {
	if x != nil {
		return x.TicketID
	}
	return ""
}

func (x *TicketAccepted) GetOrderID() string {
	if x != nil {
		return x.OrderID
	}
	return ""
}

func (x *TicketAccepted) GetAcceptedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AcceptedAt
	}
	return nil
}

func (x *TicketAccepted) GetReadyBy() *timestamppb.Timestamp {
	if x != nil {
		return x.ReadyBy
	}
	return nil
}

// commands
type CreateTicket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderID      string                   `protobuf:"bytes,1,opt,name=OrderID,proto3" json:"OrderID,omitempty"`
	RestaurantID string                   `protobuf:"bytes,2,opt,name=RestaurantID,proto3" json:"RestaurantID,omitempty"`
	Items        []*CreateTicket_LineItem `protobuf:"bytes,3,rep,name=Items,proto3" json:"Items,omitempty"`
}

func (x *CreateTicket) Reset() {
	*x = CreateTicket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kitchenpb_kitchen_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTicket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTicket) ProtoMessage() {}

func (x *CreateTicket) ProtoReflect() protoreflect.Message {
	mi := &file_kitchenpb_kitchen_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTicket.ProtoReflect.Descriptor instead.
func (*CreateTicket) Descriptor() ([]byte, []int) {
	return file_kitchenpb_kitchen_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTicket) GetOrderID() string {
	if x != nil {
		return x.OrderID
	}
	return ""
}

func (x *CreateTicket) GetRestaurantID() string {
	if x != nil {
		return x.RestaurantID
	}
	return ""
}

func (x *CreateTicket) GetItems() []*CreateTicket_LineItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ConfirmCreateTicket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TicketID string `protobuf:"bytes,1,opt,name=TicketID,proto3" json:"TicketID,omitempty"`
}

func (x *ConfirmCreateTicket) Reset() {
	*x = ConfirmCreateTicket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kitchenpb_kitchen_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmCreateTicket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmCreateTicket) ProtoMessage() {}

func (x *ConfirmCreateTicket) ProtoReflect() protoreflect.Message {
	mi := &file_kitchenpb_kitchen_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmCreateTicket.ProtoReflect.Descriptor instead.
func (*ConfirmCreateTicket) Descriptor() ([]byte, []int) {
	return file_kitchenpb_kitchen_messages_proto_rawDescGZIP(), []int{2}
}

func (x *ConfirmCreateTicket) GetTicketID() string {
	if x != nil {
		return x.TicketID
	}
	return ""
}

type CancelCreateTicket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TicketID string `protobuf:"bytes,1,opt,name=TicketID,proto3" json:"TicketID,omitempty"`
}

func (x *CancelCreateTicket) Reset() {
	*x = CancelCreateTicket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kitchenpb_kitchen_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelCreateTicket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelCreateTicket) ProtoMessage() {}

func (x *CancelCreateTicket) ProtoReflect() protoreflect.Message {
	mi := &file_kitchenpb_kitchen_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelCreateTicket.ProtoReflect.Descriptor instead.
func (*CancelCreateTicket) Descriptor() ([]byte, []int) {
	return file_kitchenpb_kitchen_messages_proto_rawDescGZIP(), []int{3}
}

func (x *CancelCreateTicket) GetTicketID() string {
	if x != nil {
		return x.TicketID
	}
	return ""
}

// Replies
type CreatedTicket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreatedTicket) Reset() {
	*x = CreatedTicket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kitchenpb_kitchen_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatedTicket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatedTicket) ProtoMessage() {}

func (x *CreatedTicket) ProtoReflect() protoreflect.Message {
	mi := &file_kitchenpb_kitchen_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatedTicket.ProtoReflect.Descriptor instead.
func (*CreatedTicket) Descriptor() ([]byte, []int) {
	return file_kitchenpb_kitchen_messages_proto_rawDescGZIP(), []int{4}
}

func (x *CreatedTicket) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateTicket_LineItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MenuItemID string `protobuf:"bytes,1,opt,name=MenuItemID,proto3" json:"MenuItemID,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Quantity   int64  `protobuf:"varint,3,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
}

func (x *CreateTicket_LineItem) Reset() {
	*x = CreateTicket_LineItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kitchenpb_kitchen_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTicket_LineItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTicket_LineItem) ProtoMessage() {}

func (x *CreateTicket_LineItem) ProtoReflect() protoreflect.Message {
	mi := &file_kitchenpb_kitchen_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTicket_LineItem.ProtoReflect.Descriptor instead.
func (*CreateTicket_LineItem) Descriptor() ([]byte, []int) {
	return file_kitchenpb_kitchen_messages_proto_rawDescGZIP(), []int{1, 0}
}

func (x *CreateTicket_LineItem) GetMenuItemID() string {
	if x != nil {
		return x.MenuItemID
	}
	return ""
}

func (x *CreateTicket_LineItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTicket_LineItem) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

var File_kitchenpb_kitchen_messages_proto protoreflect.FileDescriptor

var file_kitchenpb_kitchen_messages_proto_rawDesc = []byte{
	0x0a, 0x20, 0x6b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x70, 0x62, 0x2f, 0x6b, 0x69, 0x74, 0x63,
	0x68, 0x65, 0x6e, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x09, 0x6b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x70, 0x62, 0x1a, 0x1f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb8,
	0x01, 0x0a, 0x0e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x44, 0x12, 0x18, 0x0a,
	0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x44, 0x12, 0x3a, 0x0a, 0x0a, 0x41, 0x63, 0x63, 0x65, 0x70,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x12, 0x34, 0x0a, 0x07, 0x52, 0x65, 0x61, 0x64, 0x79, 0x42, 0x79, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x07, 0x52, 0x65, 0x61, 0x64, 0x79, 0x42, 0x79, 0x22, 0xe0, 0x01, 0x0a, 0x0c, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61,
	0x6e, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x52, 0x65, 0x73, 0x74,
	0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x36, 0x0a, 0x05, 0x49, 0x74, 0x65, 0x6d,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6b, 0x69, 0x74, 0x63, 0x68, 0x65,
	0x6e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74,
	0x2e, 0x4c, 0x69, 0x6e, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73,
	0x1a, 0x5a, 0x0a, 0x08, 0x4c, 0x69, 0x6e, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1e, 0x0a, 0x0a,
	0x4d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x31, 0x0a, 0x13,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x44, 0x22,
	0x30, 0x0a, 0x12, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49,
	0x44, 0x22, 0x1f, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x42, 0xa7, 0x01, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x2e, 0x6b, 0x69, 0x74, 0x63, 0x68,
	0x65, 0x6e, 0x70, 0x62, 0x42, 0x14, 0x4b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x3c, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x65, 0x7a, 0x61, 0x41, 0x6d, 0x69,
	0x72, 0x69, 0x31, 0x32, 0x33, 0x2f, 0x66, 0x74, 0x67, 0x6f, 0x67, 0x6f, 0x56, 0x33, 0x2f, 0x6b,
	0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x2f, 0x6b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x70, 0x62,
	0x2f, 0x6b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x70, 0x62, 0xa2, 0x02, 0x03, 0x4b, 0x58, 0x58,
	0xaa, 0x02, 0x09, 0x4b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x70, 0x62, 0xca, 0x02, 0x09, 0x4b,
	0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x70, 0x62, 0xe2, 0x02, 0x15, 0x4b, 0x69, 0x74, 0x63, 0x68,
	0x65, 0x6e, 0x70, 0x62, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0xea, 0x02, 0x09, 0x4b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kitchenpb_kitchen_messages_proto_rawDescOnce sync.Once
	file_kitchenpb_kitchen_messages_proto_rawDescData = file_kitchenpb_kitchen_messages_proto_rawDesc
)

func file_kitchenpb_kitchen_messages_proto_rawDescGZIP() []byte {
	file_kitchenpb_kitchen_messages_proto_rawDescOnce.Do(func() {
		file_kitchenpb_kitchen_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_kitchenpb_kitchen_messages_proto_rawDescData)
	})
	return file_kitchenpb_kitchen_messages_proto_rawDescData
}

var file_kitchenpb_kitchen_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_kitchenpb_kitchen_messages_proto_goTypes = []interface{}{
	(*TicketAccepted)(nil),        // 0: kitchenpb.TicketAccepted
	(*CreateTicket)(nil),          // 1: kitchenpb.CreateTicket
	(*ConfirmCreateTicket)(nil),   // 2: kitchenpb.ConfirmCreateTicket
	(*CancelCreateTicket)(nil),    // 3: kitchenpb.CancelCreateTicket
	(*CreatedTicket)(nil),         // 4: kitchenpb.CreatedTicket
	(*CreateTicket_LineItem)(nil), // 5: kitchenpb.CreateTicket.LineItem
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_kitchenpb_kitchen_messages_proto_depIdxs = []int32{
	6, // 0: kitchenpb.TicketAccepted.AcceptedAt:type_name -> google.protobuf.Timestamp
	6, // 1: kitchenpb.TicketAccepted.ReadyBy:type_name -> google.protobuf.Timestamp
	5, // 2: kitchenpb.CreateTicket.Items:type_name -> kitchenpb.CreateTicket.LineItem
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_kitchenpb_kitchen_messages_proto_init() }
func file_kitchenpb_kitchen_messages_proto_init() {
	if File_kitchenpb_kitchen_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kitchenpb_kitchen_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TicketAccepted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kitchenpb_kitchen_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTicket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kitchenpb_kitchen_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfirmCreateTicket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kitchenpb_kitchen_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelCreateTicket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kitchenpb_kitchen_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatedTicket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kitchenpb_kitchen_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTicket_LineItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kitchenpb_kitchen_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kitchenpb_kitchen_messages_proto_goTypes,
		DependencyIndexes: file_kitchenpb_kitchen_messages_proto_depIdxs,
		MessageInfos:      file_kitchenpb_kitchen_messages_proto_msgTypes,
	}.Build()
	File_kitchenpb_kitchen_messages_proto = out.File
	file_kitchenpb_kitchen_messages_proto_rawDesc = nil
	file_kitchenpb_kitchen_messages_proto_goTypes = nil
	file_kitchenpb_kitchen_messages_proto_depIdxs = nil
}
