version: "3.8"

services:
  #
  # docker compose --profile monolith up
  # docker compose up
  #
  monolith:
    container_name: monolith
    hostname: monolith
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - '8000:8000'
      - '8085:8085'
    env_file:
      - docker/.env
    depends_on:
      - postgres
    command: [ "./wait-for", "postgres:5432", "--", "/ftgogo/monolith" ]
    profiles: [ monolith ]
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=itsasecret
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
      - './docker/database:/docker-entrypoint-initdb.d'
  nats:
    container_name: nats
    hostname: nats
    image: nats:2-alpine
    ports:
      - '4222:4222'
      - '8222:8222'      
    command:
      - -js
      - -sd
      - /var/lib/nats/data
      - -m 
      - '8222'
    volumes:
      - 'jsdata:/var/lib/nats/data'

volumes:
  pgdata:
  jsdata:  