// Code generated by mockery v2.33.0. DO NOT EDIT.

package orderpb

import mock "github.com/stretchr/testify/mock"

// MockUnsafeOrderServiceServer is an autogenerated mock type for the UnsafeOrderServiceServer type
type MockUnsafeOrderServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedOrderServiceServer provides a mock function with given fields:
func (_m *MockUnsafeOrderServiceServer) mustEmbedUnimplementedOrderServiceServer() {
	_m.Called()
}

// NewMockUnsafeOrderServiceServer creates a new instance of MockUnsafeOrderServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnsafeOrderServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnsafeOrderServiceServer {
	mock := &MockUnsafeOrderServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
