// Code generated by mockery v2.33.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/rezaAmiri123/ftgogoV3/consumer/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// ConsumerRepository is an autogenerated mock type for the ConsumerRepository type
type ConsumerRepository struct {
	mock.Mock
}

// Find provides a mock function with given fields: ctx, consumerID
func (_m *ConsumerRepository) Find(ctx context.Context, consumerID string) (*domain.Consumer, error) {
	ret := _m.Called(ctx, consumerID)

	var r0 *domain.Consumer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Consumer, error)); ok {
		return rf(ctx, consumerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Consumer); ok {
		r0 = rf(ctx, consumerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Consumer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, consumerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, consumer
func (_m *ConsumerRepository) Save(ctx context.Context, consumer *domain.Consumer) error {
	ret := _m.Called(ctx, consumer)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Consumer) error); ok {
		r0 = rf(ctx, consumer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, consumer
func (_m *ConsumerRepository) Update(ctx context.Context, consumer *domain.Consumer) error {
	ret := _m.Called(ctx, consumer)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Consumer) error); ok {
		r0 = rf(ctx, consumer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewConsumerRepository creates a new instance of ConsumerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsumerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConsumerRepository {
	mock := &ConsumerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
