// Code generated by mockery v2.33.0. DO NOT EDIT.

package domain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRestaurantRepository is an autogenerated mock type for the RestaurantRepository type
type MockRestaurantRepository struct {
	mock.Mock
}

// Find provides a mock function with given fields: ctx, restaurantID
func (_m *MockRestaurantRepository) Find(ctx context.Context, restaurantID string) (*Restaurant, error) {
	ret := _m.Called(ctx, restaurantID)

	var r0 *Restaurant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*Restaurant, error)); ok {
		return rf(ctx, restaurantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *Restaurant); ok {
		r0 = rf(ctx, restaurantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Restaurant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, restaurantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockRestaurantRepository creates a new instance of MockRestaurantRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRestaurantRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRestaurantRepository {
	mock := &MockRestaurantRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
