// Code generated by mockery v2.33.0. DO NOT EDIT.

package domain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockConsumerRepository is an autogenerated mock type for the ConsumerRepository type
type MockConsumerRepository struct {
	mock.Mock
}

// ValidateOrderByConsumer provides a mock function with given fields: ctx, validate
func (_m *MockConsumerRepository) ValidateOrderByConsumer(ctx context.Context, validate ValidateOrderByConsumer) error {
	ret := _m.Called(ctx, validate)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ValidateOrderByConsumer) error); ok {
		r0 = rf(ctx, validate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockConsumerRepository creates a new instance of MockConsumerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConsumerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConsumerRepository {
	mock := &MockConsumerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
