// Code generated by mockery v2.33.0. DO NOT EDIT.

package domain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockDeliveryRepository is an autogenerated mock type for the DeliveryRepository type
type MockDeliveryRepository struct {
	mock.Mock
}

// CreateDelivery provides a mock function with given fields: ctx, create
func (_m *MockDeliveryRepository) CreateDelivery(ctx context.Context, create CreateDelivery) error {
	ret := _m.Called(ctx, create)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, CreateDelivery) error); ok {
		r0 = rf(ctx, create)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockDeliveryRepository creates a new instance of MockDeliveryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeliveryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeliveryRepository {
	mock := &MockDeliveryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
