// Code generated by mockery v2.33.0. DO NOT EDIT.

package domain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAccountRepository is an autogenerated mock type for the AccountRepository type
type MockAccountRepository struct {
	mock.Mock
}

// AuthorizeOrderByAccount provides a mock function with given fields: ctx, validate
func (_m *MockAccountRepository) AuthorizeOrderByAccount(ctx context.Context, validate AuthorizeOrderByAccount) error {
	ret := _m.Called(ctx, validate)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, AuthorizeOrderByAccount) error); ok {
		r0 = rf(ctx, validate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockAccountRepository creates a new instance of MockAccountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountRepository {
	mock := &MockAccountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
