global:
  evaluation_interval: 30s
  scrape_interval: 5s
scrape_configs:
  - job_name: monolotith
    scrape_interval: 10s
    static_configs:
      - targets:
        - 'monolith:8000'
  - job_name: otel
    static_configs:
      - targets:
          - 'collector:9464'
  - job_name: otel-collector
    static_configs:
      - targets:
          - 'collector:8888'
