// Code generated by mockery v2.33.0. DO NOT EDIT.

package mocks

import (
	context "context"

	ddd "github.com/rezaAmiri123/ftgogoV3/internal/ddd"
	mock "github.com/stretchr/testify/mock"
)

// EventPublisher is an autogenerated mock type for the EventPublisher type
type EventPublisher[T ddd.Event] struct {
	mock.Mock
}

// Publish provides a mock function with given fields: ctx, events
func (_m *EventPublisher[T]) Publish(ctx context.Context, events ...T) error {
	_va := make([]interface{}, len(events))
	for _i := range events {
		_va[_i] = events[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...T) error); ok {
		r0 = rf(ctx, events...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewEventPublisher creates a new instance of EventPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventPublisher[T ddd.Event](t interface {
	mock.TestingT
	Cleanup(func())
}) *EventPublisher[T] {
	mock := &EventPublisher[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
