name: node

on:
  push:
    branches: [ "node" ]

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Run 
        run: |       
          npm install -g @asyncapi/cli
          npm install -g @asyncapi/html-template@2.1.7
          cd consumer/consumerpb
          asyncapi generate fromTemplate asyncapi.yaml @asyncapi/html-template -o . --force-write
          cd ../..
       
          git config --global user.name "action-user"
          git config --global user.email "action-user@example.com"
          git add .
          result=$(git status | grep "nothing to commit, working tree clean" |wc -l )
          if [[ $result -eq 0 ]]
            then
            git commit -m "update node "
            git push origin node
          fi
          
